### ISSUE TITLE
need encryption for protect from hack

### ISSUE THREAD

**Issue by netpyoung** [neuecc/MasterMemory#6]

**Comment by neuecc** [comment]
`Database.Save()` returns byte[] so you can encrypt retunred byte[].
and when open, `Database.Open(byte[] bytes)` accepts byte[] so pass the decrypted byte[].

**Comment by netpyoung** [comment]
I know that, but I worried about memory hack.

how about that like?
 https://github.com/has-taiar/SQLite.Net.Cipher

**Comment by neuecc** [comment]
interesting, but very difficult.
Because mastermemory's inmemory(decoded) data is pure raw.
If you always apply encryption, performance will fall dreadfully.

**Comment by netpyoung** [comment]
@neuecc  okay I understand. i forgot close this issue.
